project:
  type: website
  output-dir: docs
website:
  title: "Dominik Schulz"
  search: false
  navbar:
    logo: avatarCircleSmall.png
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:publications
      - text: "Teaching"
        href: teachings.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - text: "Impressum & Datenschutzerklärung"
        href: impressum.qmd
  sidebar:
    - id: publications
      title: "Publications"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - research_articles.qmd
        - published_software.qmd
        - conferences.qmd

format:
  html:
    theme:
      light: flatly
    css: styles.css

editor: visual

