---
title: "Curriculum Vitae"
page-layout: full
title-block-banner: false
---

## Job history

<div class="job-card-container">
<div class="job-card">
<p class="job-header">
Scientific Employee
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Period:
</p>
</div>
<div class="col2">
<p class="job-text">
Oct 2021 - Mar 2026
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Department:
</p>
</div>
<div class="col2">
<p class="job-text">
Chair of Econometrics and Quantitative Methods, Faculty of Business Administration and Economics
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Employer:
</p>
</div>
<div class="col2">
<p class="job-text">
Paderborn University, Germany
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Details:
</p>
</div>
<div class="col2">
<p class="job-text">
Data modelling, researching new time series models, simulation studies, programming and publishing of R software, planning and conducting tutorials and lectures
</p>
</div>
</div>

</div>
</div>



<div class="job-card-container">
<div class="job-card">
<p class="job-header">
Student Assistant
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Period:
</p>
</div>
<div class="col2">
<p class="job-text">
Mar 2019 - Sep 2021
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Department:
</p>
</div>
<div class="col2">
<p class="job-text">
Chair of Econometrics and Quantitative Methods, Faculty of Business Administration and Economics
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Employer:
</p>
</div>
<div class="col2">
<p class="job-text">
Paderborn University, Germany
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Details:
</p>
</div>
<div class="col2">
<p class="job-text">
Data modelling, programming and publishing of R software, planning and conducting tutorials
</p>
</div>
</div>

</div>
</div>



<div class="job-card-container">
<div class="job-card">
<p class="job-header">
Intern
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Period:
</p>
</div>
<div class="col2">
<p class="job-text">
Aug 2018 - Sep 2018
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Department:
</p>
</div>
<div class="col2">
<p class="job-text">
Agriculture, environment, foreign
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Employer:
</p>
</div>
<div class="col2">
<p class="job-text">
Federal Statistical Office, Germany
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Details:
</p>
</div>
<div class="col2">
<p class="job-text">
SAS programming, environmental accounts, controlling received data packages, updating publications about structural data on water management
</p>
</div>
</div>

</div>
</div>






<br>

## Education

<div class="job-card-container">
<div class="job-card">
<p class="job-header">
Doctoral studies (finished)
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Institution:
</p>
</div>
<div class="col2">
<p class="job-text">
Faculty of Business Administration and Economics, Paderborn University, Germany
</p>
</div>
</div>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Thesis topic:
</p>
</div>
<div class="col2">
<p class="job-text">
New Implementations in R for Parametric and Semiparametric Modelling of Univariate and Spatial Short- and Long-Memory Time Series
</p>
</div>
</div>

</div>
</div>


<div class="job-card-container">
<div class="job-card">
<p class="job-header">
M.Sc. International Economics and Management (finished)
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Institution:
</p>
</div>
<div class="col2">
<p class="job-text">
Faculty of Business Administration and Economics, Paderborn University, Germany
</p>
</div>
</div>

</div>
</div>

<div class="job-card-container">
<div class="job-card">
<p class="job-header">
Study semester abroad
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Institution:
</p>
</div>
<div class="col2">
<p class="job-text">
La Facultad de Ciencias Económicas y Empresariales, Universidad de Granada, Spain
</p>
</div>
</div>

</div>
</div>



<div class="job-card-container">
<div class="job-card">
<p class="job-header">
B.Sc. International Business Studies (finished)
</p>

<div class="col-container">
<div class="col1">
<p class="job-ind">
Institution:
</p>
</div>
<div class="col2">
<p class="job-text">
Faculty of Business Administration and Economics, Paderborn University, Germany
</p>
</div>
</div>

</div>
</div>
